path: C:\Users\USER\Documents\UofC\Fall 2024\ENGG 680\Project\Traffic Sign\Traffic Sign\Traffic-sign-detection-using-yolo\data
train: C:\Users\USER\Documents\UofC\Fall 2024\ENGG 680\Project\Traffic Sign\Traffic Sign\Traffic-sign-detection-using-yolo\data\images\train
val: C:\Users\USER\Documents\UofC\Fall 2024\ENGG 680\Project\Traffic Sign\Traffic Sign\Traffic-sign-detection-using-yolo\data\images\val
nc: 9
names:
  0: Speed limit Sign 30
  1: Speed limit Sign 50
  2: Yield Sign
  3: Stop Sign
  4: Other Traffic signs
  5: Cars
  6: Pedestrians
  7: traffic light
  8: Park Sign